"""
templates.py
------------
Template-based Natural Language Generation (NLG) bank for the Smart
Academic Email Generator.

Each intent maps to:
    - a subject line template
    - a body template with placeholders

Placeholders are filled in by email_generator.py using values produced by
the NLP pipeline (entities, keywords, urgency, dates, reason phrase).
This is classical, deterministic NLG -- no text is generated by a
language model. All variability comes from slot-filling and simple
conditional logic (e.g. urgency phrasing, greeting salutation).

Placeholder legend:
    {teacher_name}   - salutation name
    {student_name}   - signing name
    {roll_number}    - roll number (optional)
    {department}     - department (optional)
    {date}           - date of the event/absence
    {reason_phrase}  - human-readable reason built from keywords/entities
    {duration}       - duration phrase e.g. "2 days" (optional)
    {urgency_line}   - extra urgency sentence (optional, inserted if High)
"""

SUBJECT_TEMPLATES = {
    "medical_leave": "Leave Application Due to Medical Reason{date_suffix}",
    "family_emergency": "Leave Application Due to Family Emergency{date_suffix}",
    "club_activity": "Permission Request for Club Activity{date_suffix}",
    "technical_competition": "Permission Request for Technical Competition{date_suffix}",
    "hackathon": "Permission Request to Participate in Hackathon{date_suffix}",
    "sports_event": "Permission Request for Sports Event{date_suffix}",
    "nss_activity": "Permission Request for NSS Activity{date_suffix}",
    "industrial_visit": "Permission Request for Industrial Visit{date_suffix}",
    "internship": "Leave Application for Internship Joining{date_suffix}",
    "permission_request": "Request for Permission{date_suffix}",
    "assignment_extension": "Request for Extension of Assignment Deadline",
    "project_deadline_extension": "Request for Extension of Project Deadline",
    "apology_absence": "Apology for Absence{date_suffix}",
    "thank_you": "Thank You",
    "meeting_request": "Request for a Meeting",
}

BODY_TEMPLATES = {
    "medical_leave": (
        "Respected {teacher_name},\n\n"
        "I hope this email finds you well. I am writing to inform you that {reason_phrase}. "
        "{urgency_line}Due to this, I was unable to attend classes{date_clause}. "
        "I kindly request you to grant me leave for the same and treat this as an official intimation. "
        "I will make sure to cover the missed academic work at the earliest.\n\n"
        "Thank you for your understanding and support.\n\n"
        "Regards,\n{student_name}{roll_line}{dept_line}"
    ),
    "family_emergency": (
        "Respected {teacher_name},\n\n"
        "I am writing to inform you that {reason_phrase}. "
        "{urgency_line}Because of this family emergency, I was unable to attend college{date_clause}. "
        "I request you to kindly grant me leave and excuse my absence during this period. "
        "I will complete any pending work as soon as I am able to.\n\n"
        "Thank you for your consideration.\n\n"
        "Regards,\n{student_name}{roll_line}{dept_line}"
    ),
    "club_activity": (
        "Respected {teacher_name},\n\n"
        "I would like to inform you that {reason_phrase}. "
        "This activity requires my presence{date_clause}. "
        "I kindly request your permission to be excused from class for this purpose. "
        "I assure you that I will catch up on any academic work I miss.\n\n"
        "Thank you for your support.\n\n"
        "Regards,\n{student_name}{roll_line}{dept_line}"
    ),
    "technical_competition": (
        "Respected {teacher_name},\n\n"
        "I am pleased to inform you that {reason_phrase}. "
        "I request your kind permission to participate in this event{date_clause}, "
        "as it will be a valuable learning experience and an opportunity to represent our college. "
        "I will ensure that my academic work does not suffer because of this.\n\n"
        "Thank you for your encouragement and support.\n\n"
        "Regards,\n{student_name}{roll_line}{dept_line}"
    ),
    "hackathon": (
        "Respected {teacher_name},\n\n"
        "I am excited to share that {reason_phrase}. "
        "I request your permission to attend this hackathon{date_clause}, as it is a great opportunity "
        "to apply my technical skills and gain practical exposure. "
        "I will complete any academic work I miss as soon as possible.\n\n"
        "Thank you for your support and encouragement.\n\n"
        "Regards,\n{student_name}{roll_line}{dept_line}"
    ),
    "sports_event": (
        "Respected {teacher_name},\n\n"
        "I am writing to inform you that {reason_phrase}. "
        "I kindly request your permission to participate{date_clause}, as this is an important opportunity "
        "to represent our college in sports. "
        "I will make sure to complete any missed academic work promptly.\n\n"
        "Thank you for your understanding.\n\n"
        "Regards,\n{student_name}{roll_line}{dept_line}"
    ),
    "nss_activity": (
        "Respected {teacher_name},\n\n"
        "I would like to inform you that {reason_phrase} as part of the NSS programme. "
        "I request your permission to be excused from class{date_clause} to take part in this activity. "
        "I will complete any pending academic work at the earliest.\n\n"
        "Thank you for your support.\n\n"
        "Regards,\n{student_name}{roll_line}{dept_line}"
    ),
    "industrial_visit": (
        "Respected {teacher_name},\n\n"
        "I am writing to inform you that {reason_phrase}. "
        "I request your permission to attend this visit{date_clause}, as it will provide valuable "
        "practical exposure related to our curriculum. "
        "I will ensure my regular academic work is not affected.\n\n"
        "Thank you for your consideration.\n\n"
        "Regards,\n{student_name}{roll_line}{dept_line}"
    ),
    "internship": (
        "Respected {teacher_name},\n\n"
        "I am pleased to inform you that {reason_phrase}. "
        "I request your permission and guidance regarding leave{date_clause} so that I may join this "
        "opportunity, which will greatly contribute to my practical learning and career growth. "
        "I will keep you informed of my progress.\n\n"
        "Thank you for your support and guidance.\n\n"
        "Regards,\n{student_name}{roll_line}{dept_line}"
    ),
    "permission_request": (
        "Respected {teacher_name},\n\n"
        "I am writing to request your permission regarding the following: {reason_phrase}. "
        "{urgency_line}I would be grateful if you could kindly approve this request{date_clause}.\n\n"
        "Thank you for your consideration.\n\n"
        "Regards,\n{student_name}{roll_line}{dept_line}"
    ),
    "assignment_extension": (
        "Respected {teacher_name},\n\n"
        "I am writing to request an extension for the submission of my assignment. "
        "{reason_phrase_cap}, and as a result I was unable to complete the assignment within the given "
        "deadline{date_clause}. I kindly request a short extension so that I can submit quality work. "
        "I apologize for any inconvenience caused.\n\n"
        "Thank you for your understanding.\n\n"
        "Regards,\n{student_name}{roll_line}{dept_line}"
    ),
    "project_deadline_extension": (
        "Respected {teacher_name},\n\n"
        "I am writing to request an extension for my project submission deadline. "
        "{reason_phrase_cap}, which has delayed the completion of my project work{date_clause}. "
        "I kindly request a short extension to ensure the project meets the expected standard. "
        "I apologize for any inconvenience this may cause.\n\n"
        "Thank you for your understanding and support.\n\n"
        "Regards,\n{student_name}{roll_line}{dept_line}"
    ),
    "apology_absence": (
        "Respected {teacher_name},\n\n"
        "I am extremely sorry for my absence{date_clause}. {reason_phrase_cap}, due to which I could not "
        "attend the class/lab. I sincerely apologize for any inconvenience this may have caused and "
        "request you to kindly excuse my absence. "
        "I will make sure to complete any missed work at the earliest.\n\n"
        "Thank you for your understanding.\n\n"
        "Regards,\n{student_name}{roll_line}{dept_line}"
    ),
    "thank_you": (
        "Respected {teacher_name},\n\n"
        "I would like to sincerely thank you for {reason_phrase}. "
        "Your support and guidance have meant a great deal to me, and I truly appreciate the time and "
        "effort you have taken.\n\n"
        "Thank you once again.\n\n"
        "Regards,\n{student_name}{roll_line}{dept_line}"
    ),
    "meeting_request": (
        "Respected {teacher_name},\n\n"
        "I hope you are doing well. I would like to request a meeting with you regarding {reason_phrase}. "
        "Kindly let me know a convenient time{date_clause} when we could discuss this in person.\n\n"
        "Thank you for your time and consideration.\n\n"
        "Regards,\n{student_name}{roll_line}{dept_line}"
    ),
}


def get_subject_template(intent: str) -> str:
    return SUBJECT_TEMPLATES.get(intent, "Request for {reason_phrase}")


def get_body_template(intent: str) -> str:
    return BODY_TEMPLATES.get(
        intent,
        (
            "Respected {teacher_name},\n\n"
            "I am writing regarding {reason_phrase}{date_clause}. "
            "I kindly request your consideration in this matter.\n\n"
            "Thank you.\n\nRegards,\n{student_name}{roll_line}{dept_line}"
        ),
    )
